import ProtectedRoute from "../components/ProtectedRoute";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ProtectedRoute>{children}</ProtectedRoute>
        </StoreProvider>
      </body>
    </html>
  );
}
